# Generated by Django 2.0 on 2020-02-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.TextField(max_length=250)),
                ('comarca', models.TextField(max_length=250)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
